apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: openpanelproviderstacks.crossplane.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: crossplane.ops.com.ai/v1alpha1
    kind: OpenPanelProviderStack
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-crossplane-openpanel-provider-stackrender
    step: render
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
