apiVersion: hops.ops.com.ai/v1alpha1
kind: CrossplaneOpenPanelProvider
metadata:
  name: openpanel
  namespace: default
spec:
  clusterName: my-cluster
  kubernetesProviderConfigRef:
    name: my-cluster

